#!/usr/bin/env bash
set -e
TARGET=${1:-40}        # 목표 커버리지 (기본 40%)
SLEEP=${2:-3}          # 각 사이클 간 대기 시간(초)

read_rate() {
  # 1) Istanbul summary (generated by coverage-v8)
  if [ -f coverage/coverage-summary.json ]; then
    node -e "try{let s=require('./coverage/coverage-summary.json');console.log(s.total?.lines?.pct ?? 0)}catch(e){console.log(0)}"
    return
  fi
  # 2) Vitest JSON reporter (fallback)
  if [ -f .coverage-last.json ]; then
    node -e "try{let r=require('./.coverage-last.json');console.log(r.total?.lines?.pct ?? 0)}catch(e){console.log(0)}"
    return
  fi
  echo 0
}

while true; do
  npm run test:coverage -s >/dev/null 2>&1 || true

  RATE=$(read_rate)
  printf '📊 현재 커버리지: %.2f%%\n' "$RATE"

  # 목표 달성 여부 체크
  if awk -v r="$RATE" -v t="$TARGET" 'BEGIN{exit (r>=t)?0:1}'; then
    echo "✅ 목표 ${TARGET}% 달성 완료. 자동 종료."
    break
  fi

  # 자동 커밋 (선택)
  git add -A && git commit -m "test(auto): coverage ${RATE}%" >/dev/null 2>&1 || true

  sleep "$SLEEP"
done
